version: '3.8'

services:
  app_points:
    depends_on:
      - "postgres"
    image: static_collector
    build: .
    restart: no
    env_file:
      - .env
    ports:
      - 2137:2137
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432


